# Generated by Django 4.0.1 on 2022-02-28 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_books_image_alter_employee_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='status',
            field=models.CharField(choices=[('incart', 'incart'), ('cancelled', 'cancelled'), ('order_placed', 'order_placed')], default='incart', max_length=150),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('dispatched', 'dispatched'), ('in_transit', 'in_transit'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='order_placed', max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
